name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: DeterminateSystems/flake-checker-action@v10
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix develop -c cargo ws exec --no-bail -- cargo rdme --force
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate README"
          default_author: github_actions
      - run: nix develop -c cargo clippy --all-features --fix --no-deps
      - run: nix fmt
      - run: nix develop -c cargo doc --all-features --no-deps
      - run: nix develop -c cargo test --all-features --all-targets
